# Generated by Django 5.1.15 on 2026-09-26 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='leavetype',
            name='staff_lt_accrual_active_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='staff_leave_leave_t_0ec8fb_idx',
            old_name='staff_lr_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewhistory',
            new_name='staff_revie_actor_i_a7f890_idx',
            old_name='staff_review_actor_created_idx',
        ),
        migrations.RenameIndex(
            model_name='workreport',
            new_name='staff_work__status_c9e013_idx',
            old_name='staff_wr_status_date_idx',
        ),
        migrations.AlterField(
            model_name='workreport',
            name='timesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_reports', to='staff.timesheetentry'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_staff_leave_type_code_alive'),
        ),
    ]
