# Generated by Django 5.1.15 on 2026-09-24 03:39

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count
from django.utils import timezone


def archive_duplicate_pending_tasks(apps, schema_editor):
    """Keep one actionable row and retain any legacy duplicates as history."""
    WorkflowTask = apps.get_model("tasks", "WorkflowTask")
    alias = schema_editor.connection.alias
    pending = WorkflowTask.objects.using(alias).filter(
        is_deleted=False, status="pending",
    )
    groups = pending.values("instance_id", "state_id", "assignee_id").annotate(
        row_count=Count("id"),
    ).filter(row_count__gt=1)
    for group in groups.iterator():
        rows = pending.filter(
            instance_id=group["instance_id"],
            state_id=group["state_id"],
            assignee_id=group["assignee_id"],
        ).order_by("created_at", "id")
        keep_id = rows.values_list("id", flat=True).first()
        rows.exclude(id=keep_id).update(
            status="skipped", completed_at=timezone.now(),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_workflowtask_escalated_at_and_more'),
        ('workflow', '0011_remove_notificationoutbox_workflow_no_status_e1e44d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(archive_duplicate_pending_tasks, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='workflowtask',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status', 'pending')), fields=('instance', 'state', 'assignee'), name='uniq_pending_task_instance_state_user'),
        ),
    ]
