# Generated by Django 5.1.15 on 2026-09-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.SlugField(help_text='Immutable business key, e.g. manager, hr, employee (یکتا در میان نقش\u200cهای زنده)', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_code',
            field=models.CharField(blank=True, help_text='کد پرسنلی — مثال: EMP-10042 (یکتا در میان کاربران زنده)', max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_accounts_role_code_alive'),
        ),
    ]
