# Generated by Django 5.1.15 on 2026-09-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_role_code_alter_user_employee_code_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_code__isnull', False), ('is_deleted', False), models.Q(('employee_code', ''), _negated=True)), fields=('employee_code',), name='uniq_user_employee_code_alive'),
        ),
    ]
