# Generated by Django 5.1.15 on 2026-08-14 20:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('national_code', models.CharField(db_index=True, help_text='کد ملی — شناسه یکتای شخص', max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('father_name', models.CharField(blank=True, default='', max_length=128)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('unspecified', 'مشخص نشده')], default='unspecified', max_length=16)),
                ('mobile', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', help_text='تلفن ثابت', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('person_type', models.CharField(choices=[('student', 'دانش\u200cآموز'), ('teacher', 'معلم / مدرس'), ('employee', 'کارمند'), ('parent', 'والدین')], db_index=True, max_length=32)),
                ('student_code', models.CharField(blank=True, help_text='کد دانش\u200cآموزی (فقط برای student)', max_length=32, null=True, unique=True)),
                ('employee_code', models.CharField(blank=True, help_text='کد پرسنلی (فقط برای employee/teacher)', max_length=32, null=True, unique=True)),
                ('department', models.CharField(blank=True, default='', max_length=128)),
                ('job_title', models.CharField(blank=True, default='', max_length=128)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/photos/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_persons', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person (هویت)',
                'verbose_name_plural': 'Persons (اشخاص)',
                'db_table': 'persons_person',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, default='', help_text='نسبت: پدر، مادر، قیم، ...', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(limit_choices_to={'person_type': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='persons.person')),
                ('student', models.ForeignKey(limit_choices_to={'person_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_of', to='persons.person')),
            ],
            options={
                'verbose_name': 'Student-Parent relation',
                'verbose_name_plural': 'Student-Parent relations',
                'db_table': 'persons_student_parent',
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['national_code'], name='persons_per_nationa_e65a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['person_type', 'is_active'], name='persons_per_person__0be5de_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='persons_per_last_na_d3e8b1_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['mobile'], name='persons_per_mobile_58b8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentparent',
            index=models.Index(fields=['parent', 'is_active'], name='persons_stu_parent__fad5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentparent',
            index=models.Index(fields=['student', 'is_active'], name='persons_stu_student_0ff2b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentparent',
            constraint=models.UniqueConstraint(fields=('parent', 'student'), name='uniq_persons_student_parent'),
        ),
    ]
