# Generated by Django 5.1.15 on 2026-08-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('-created_at',), 'permissions': [('view_person_detail', 'مشاهده جزئیات کامل شخص'), ('view_person_list', 'مشاهده لیست اشخاص'), ('create_user_for_person', 'ساخت کاربر برای شخص'), ('view_grades_report', 'مشاهده گزارش کارنامه'), ('view_attendance_report', 'مشاهده گزارش حضورغیاب'), ('view_financial_report', 'مشاهده گزارش مالی')], 'verbose_name': 'Person (هویت)', 'verbose_name_plural': 'Persons (اشخاص)'},
        ),
    ]
