# Generated by Django 5.1.15 on 2026-09-09 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_studentparent_deleted_at_studentparent_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentparent',
            name='uniq_persons_student_parent',
        ),
        migrations.AlterField(
            model_name='person',
            name='employee_code',
            field=models.CharField(blank=True, help_text='کد پرسنلی (فقط برای employee/teacher) — یکتا در میان اشخاص زنده', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_code',
            field=models.CharField(db_index=True, help_text='کد ملی — شناسه یکتای شخص (یکتا در میان اشخاص زنده)', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='student_code',
            field=models.CharField(blank=True, help_text='کد دانش\u200cآموزی (فقط برای student) — یکتا در میان اشخاص زنده', max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('national_code',), name='uniq_persons_national_code_alive'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('student_code__isnull', False)), fields=('student_code',), name='uniq_persons_student_code_alive'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_code__isnull', False), ('is_deleted', False)), fields=('employee_code',), name='uniq_persons_employee_code_alive'),
        ),
        migrations.AddConstraint(
            model_name='studentparent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('parent', 'student'), name='uniq_persons_student_parent_alive'),
        ),
    ]
