# Generated by Django 5.1.15 on 2026-09-10 12:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_remove_studentparent_uniq_persons_student_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTypeAssignment',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('student', 'دانش\u200cآموز'), ('teacher', 'معلم / مدرس'), ('employee', 'کارمند'), ('parent', 'والدین')], db_index=True, max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_person_types', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_assignments', to='persons.person')),
            ],
            options={
                'verbose_name': 'Person Type Assignment (انتساب نوع)',
                'verbose_name_plural': 'Person Type Assignments (انتساب\u200cهای نوع)',
                'db_table': 'persons_person_type_assignment',
                'ordering': ('person', 'type'),
                'indexes': [models.Index(fields=['person', 'is_active'], name='persons_per_person__b9d92a_idx'), models.Index(fields=['type', 'is_active'], name='persons_per_type_bec3de_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('person', 'type'), name='uniq_persons_type_assignment_alive')],
            },
        ),
    ]
