# Generated by Django 5.1.15 on 2026-09-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_persontypeassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('student', 'دانش\u200cآموز'), ('teacher', 'معلم / مدرس'), ('employee', 'کارمند')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='persontypeassignment',
            name='type',
            field=models.CharField(choices=[('student', 'دانش\u200cآموز'), ('teacher', 'معلم / مدرس'), ('employee', 'کارمند')], db_index=True, max_length=32),
        ),
        migrations.DeleteModel(
            name='StudentParent',
        ),
    ]
