# Generated by Django 5.1.15 on 2026-09-24 03:55

from django.db import migrations, models


def move_primary_flag_to_student_links(apps, schema_editor):
    GuardianProfile = apps.get_model("persons", "GuardianProfile")
    StudentGuardian = apps.get_model("persons", "StudentGuardian")
    alias = schema_editor.connection.alias
    primary_guardian_ids = GuardianProfile.objects.using(alias).filter(
        is_primary=True,
    ).values_list("person_id", flat=True)
    links = StudentGuardian.objects.using(alias).filter(
        is_deleted=False, guardian_id__in=primary_guardian_ids,
    ).values_list("id", "student_id")
    by_student = {}
    for link_id, student_id in links.iterator():
        by_student.setdefault(student_id, []).append(link_id)
    ambiguous = {student_id: link_ids for student_id, link_ids in by_student.items()
                 if len(link_ids) > 1}
    if ambiguous:
        sample = ", ".join(str(student_id) for student_id in list(ambiguous)[:20])
        raise RuntimeError(
            "Multiple legacy primary guardians exist for students: " + sample
            + ". Resolve these relationships before applying this migration."
        )
    for link_ids in by_student.values():
        StudentGuardian.objects.using(alias).filter(pk=link_ids[0]).update(is_primary=True)


def restore_primary_flag_noop(apps, schema_editor):
    # A global GuardianProfile flag cannot be reconstructed from a per-student link.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_person_search_and_student_parents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardianprofile',
            options={'ordering': ('person__last_name', 'person__first_name'), 'verbose_name': 'Guardian Profile (پروفایل ولی)', 'verbose_name_plural': 'Guardian Profiles (پروفایل اولیا)'},
        ),
        migrations.AddField(
            model_name='studentguardian',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='ولی اصلی این دانش\u200cآموز؛ یکتایی در سطح رابطهٔ همین دانش\u200cآموز اعمال می\u200cشود.'),
        ),
        migrations.RunPython(
            move_primary_flag_to_student_links,
            restore_primary_flag_noop,
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_primary', True)), fields=('student',), name='uniq_persons_student_primary_guardian'),
        ),
        migrations.RemoveField(
            model_name='guardianprofile',
            name='is_primary',
        ),
    ]
