# Generated by Django 5.1.15 on 2026-08-17 14:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='عنوان ترم — مثال: پاییز ۱۴۰۴', max_length=256)),
                ('start_date', models.DateField(help_text='تاریخ شروع ترم (شمسی در ورودی/خروجی)')),
                ('end_date', models.DateField(help_text='تاریخ پایان ترم')),
                ('is_current', models.BooleanField(db_index=True, default=False, help_text='آیا این ترم جاری است؟ (فقط یک ترم می\u200cتواند current=True باشد)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Academic Term (ترم تحصیلی)',
                'verbose_name_plural': 'Academic Terms (ترم\u200cهای تحصیلی)',
                'db_table': 'academics_term',
                'ordering': ('-start_date',),
                'indexes': [models.Index(fields=['is_current', 'is_active'], name='academics_t_is_curr_04482e_idx'), models.Index(fields=['start_date', 'end_date'], name='academics_t_start_d_6589d2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='chk_academics_term_dates')],
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.SlugField(help_text='کد کلاس — مثال: MATH-101-A, 7A-1404', max_length=64)),
                ('name', models.CharField(help_text='نام کلاس — مثال: ریاضی ۱ — گروه A', max_length=256)),
                ('room', models.CharField(blank=True, default='', help_text='محل برگزاری — مثال: کلاس ۲۰۱، سالن A', max_length=128)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='ظرفیت کلاس (۰ = نامحدود)')),
                ('schedule', models.JSONField(blank=True, default=dict, help_text='زمان\u200cبندی هفتگی. مثال:\n{"days": ["شنبه", "دوشنبه"], "start_time": "08:00", "end_time": "09:30"}')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('teacher', models.ForeignKey(blank=True, help_text='معلم / مدرس کلاس', limit_choices_to={'person_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_class_groups', to='persons.person')),
                ('term', models.ForeignKey(help_text='ترم تحصیلی', on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='academics.academicterm')),
            ],
            options={
                'verbose_name': 'Class Group (کلاس)',
                'verbose_name_plural': 'Class Groups (کلاس\u200cها)',
                'db_table': 'academics_class_group',
                'ordering': ('term', 'code'),
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, help_text='تاریخ ثبت\u200cنام')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('student', models.ForeignKey(help_text='دانش\u200cآموز', limit_choices_to={'person_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='persons.person')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.classgroup')),
            ],
            options={
                'verbose_name': 'Class Enrollment (ثبت\u200cنام)',
                'verbose_name_plural': 'Class Enrollments (ثبت\u200cنام\u200cها)',
                'db_table': 'academics_class_enrollment',
                'ordering': ('class_group', 'student'),
            },
        ),
        migrations.AddIndex(
            model_name='classgroup',
            index=models.Index(fields=['term', 'is_active'], name='academics_c_term_id_1c6ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='classgroup',
            index=models.Index(fields=['teacher', 'is_active'], name='academics_c_teacher_31ba6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='classgroup',
            constraint=models.UniqueConstraint(fields=('term', 'code'), name='uniq_academics_class_group_code_per_term'),
        ),
        migrations.AddIndex(
            model_name='classenrollment',
            index=models.Index(fields=['student', 'is_active'], name='academics_c_student_5005bc_idx'),
        ),
        migrations.AddIndex(
            model_name='classenrollment',
            index=models.Index(fields=['class_group', 'is_active'], name='academics_c_class_g_71f79b_idx'),
        ),
        migrations.AddConstraint(
            model_name='classenrollment',
            constraint=models.UniqueConstraint(fields=('class_group', 'student'), name='uniq_academics_enrollment'),
        ),
    ]
