# Generated by Django 5.1.15 on 2026-08-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicterm',
            options={'ordering': ('-start_date',), 'permissions': [('manage_term', 'مدیریت ترم\u200cهای تحصیلی')], 'verbose_name': 'Academic Term (ترم تحصیلی)', 'verbose_name_plural': 'Academic Terms (ترم\u200cهای تحصیلی)'},
        ),
        migrations.AlterModelOptions(
            name='classenrollment',
            options={'ordering': ('class_group', 'student'), 'permissions': [('manage_enrollment', 'مدیریت ثبت\u200cنام\u200cها')], 'verbose_name': 'Class Enrollment (ثبت\u200cنام)', 'verbose_name_plural': 'Class Enrollments (ثبت\u200cنام\u200cها)'},
        ),
        migrations.AlterModelOptions(
            name='classgroup',
            options={'ordering': ('term', 'code'), 'permissions': [('manage_class_group', 'مدیریت کلاس\u200cها'), ('view_all_class_groups', 'مشاهده همه کلاس\u200cها')], 'verbose_name': 'Class Group (کلاس)', 'verbose_name_plural': 'Class Groups (کلاس\u200cها)'},
        ),
    ]
