# Generated by Django 5.1.15 on 2026-09-01 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_academicterm_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classenrollment',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='تاریخ ثبت\u200cنام'),
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='uniq_academics_current_term'),
        ),
    ]
