# Generated by Django 5.1.15 on 2026-09-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_classenrollment_enrollment_date_and_more'),
        ('persons', '0004_remove_studentparent_uniq_persons_student_parent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classenrollment',
            name='uniq_academics_enrollment',
        ),
        migrations.RemoveConstraint(
            model_name='classgroup',
            name='uniq_academics_class_group_code_per_term',
        ),
        migrations.AddConstraint(
            model_name='classenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('class_group', 'student'), name='uniq_academics_enrollment_alive'),
        ),
        migrations.AddConstraint(
            model_name='classgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('term', 'code'), name='uniq_academics_class_group_code_per_term_alive'),
        ),
    ]
