# Generated by Django 5.1.15 on 2026-09-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_classenrollment_uniq_academics_enrollment_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classenrollment',
            index=models.Index(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=['class_group', 'enrollment_date'], name='acad_enroll_report_idx'),
        ),
    ]
