# Generated by Django 5.1.15 on 2026-09-26 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_enrollment_report_index'),
        ('education', '0009_enrollment_report_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='offering',
            field=models.ForeignKey(blank=True, help_text='برگزاری اصلی کلاس؛ دوره از همین رابطه استخراج می\u200cشود.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='education.courseoffering'),
        ),
    ]
