# Generated by Django 5.1.15 on 2026-09-10 12:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('access_denied', 'رد دسترسی'), ('download', 'دانلود فایل'), ('sensitive_read', 'خواندن داده\u200cی حساس'), ('field_change', 'تغییر فیلد حساس')], db_index=True, max_length=32)),
                ('object_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('summary', models.CharField(help_text='خلاصه\u200cی انسانی رخداد (فارسی)', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='کاربر انجام\u200cدهنده (None = ناشناس/بی\u200cاحراز هویت)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit Event (رخداد حسابرسی)',
                'verbose_name_plural': 'Audit Events (رخدادهای حسابرسی)',
                'db_table': 'core_audit_event',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['kind', 'created_at'], name='core_audit__kind_3832d5_idx'), models.Index(fields=['content_type', 'object_id'], name='core_audit__content_fc30d9_idx')],
            },
        ),
    ]
