# Generated by Django 5.1.15 on 2026-08-14 17:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.SlugField(help_text='Business key, e.g. leave-request, mission-order', max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Workflow Definition',
                'verbose_name_plural': 'Workflow Definitions',
                'db_table': 'workflow_definition',
                'ordering': ('code', 'version'),
                'indexes': [models.Index(fields=['code', 'is_active'], name='workflow_de_code_78a254_idx'), models.Index(fields=['version'], name='workflow_de_version_968f5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.SlugField(help_text='e.g. pending-manager', max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('is_initial', models.BooleanField(db_index=True, default=False)),
                ('is_final', models.BooleanField(db_index=True, default=False)),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflow.workflowdefinition')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'workflow_state',
                'ordering': ('workflow_definition', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='running', max_length=32)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to=settings.AUTH_USER_MODEL)),
                ('current_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.state')),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow.workflowdefinition')),
            ],
            options={
                'verbose_name': 'Instance',
                'verbose_name_plural': 'Instances',
                'db_table': 'workflow_instance',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(db_index=True, help_text='e.g. submit, approve, reject, cancel', max_length=64)),
                ('comment', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='workflow.instance')),
                ('from_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs_from', to='workflow.state')),
                ('to_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs_to', to='workflow.state')),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Logs',
                'db_table': 'workflow_action_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['instance', 'created_at'], name='workflow_ac_instanc_a070cc_idx'), models.Index(fields=['actor', 'created_at'], name='workflow_ac_actor_i_3cabe5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='e.g. approve, reject, submit', max_length=256)),
                ('allowed_role_codes', models.JSONField(blank=True, default=list, help_text='List of role codes allowed to perform this transition, e.g. ["manager"]')),
                ('requires_comment', models.BooleanField(default=False)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflow.state')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflow.state')),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.workflowdefinition')),
            ],
            options={
                'verbose_name': 'Transition',
                'verbose_name_plural': 'Transitions',
                'db_table': 'workflow_transition',
                'ordering': ('workflow_definition', 'from_state', 'to_state'),
                'indexes': [models.Index(fields=['workflow_definition', 'from_state'], name='workflow_tr_workflo_8caf37_idx'), models.Index(fields=['workflow_definition', 'to_state'], name='workflow_tr_workflo_d337ee_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['workflow_definition', 'is_initial'], name='workflow_st_workflo_0de964_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['workflow_definition', 'is_final'], name='workflow_st_workflo_b9bf1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('workflow_definition', 'code'), name='uniq_workflow_state_code_per_wf'),
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['workflow_definition', 'status'], name='workflow_in_workflo_59ad14_idx'),
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['requester', 'status'], name='workflow_in_request_2620d6_idx'),
        ),
        migrations.AddIndex(
            model_name='instance',
            index=models.Index(fields=['current_state'], name='workflow_in_current_6d55ef_idx'),
        ),
    ]
