# Generated by Django 5.1.15 on 2026-08-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instance',
            options={'ordering': ('-created_at',), 'permissions': [('view_all_instances', 'مشاهده همه درخواست\u200cها'), ('approve_instance', 'تأیید درخواست'), ('cancel_any_instance', 'لغو هر درخواست')], 'verbose_name': 'Instance', 'verbose_name_plural': 'Instances'},
        ),
        migrations.AlterModelOptions(
            name='workflowdefinition',
            options={'ordering': ('code', 'version'), 'permissions': [('manage_workflow_definition', 'مدیریت تعاریف فرآیند')], 'verbose_name': 'Workflow Definition', 'verbose_name_plural': 'Workflow Definitions'},
        ),
    ]
