# Generated by Django 5.1.15 on 2026-08-25 17:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow', '0002_alter_instance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='guard_expression',
            field=models.JSONField(blank=True, default=dict, help_text='Optional guard conditions as JSON. Examples:\n{"type": "always_true"}\n{"type": "role_not_in", "roles": ["manager"], "field": "requester"}\n{"type": "entity_field_lt", "field": "enrolled_count", "other_field": "capacity"}\n{"type": "all", "guards": [...]}\n{"type": "any", "guards": [...]}\nEmpty/{} = always true (allow). Unknown type = deny (fail closed).'),
        ),
        migrations.CreateModel(
            name='EntityWorkflow',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.UUIDField(db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='workflow.instance')),
            ],
            options={
                'verbose_name': 'Entity Workflow Link',
                'verbose_name_plural': 'Entity Workflow Links',
                'db_table': 'workflow_entity_link',
                'indexes': [models.Index(fields=['instance', 'content_type'], name='workflow_en_instanc_b7fa19_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='uniq_workflow_entity_link')],
            },
        ),
    ]
