# Generated by Django 5.1.15 on 2026-08-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow', '0003_transition_guard_expression_entityworkflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={'ordering': ('-created_at',), 'verbose_name': 'Action Log (تاریخچه)', 'verbose_name_plural': 'Action Logs (تاریخچه\u200cها)'},
        ),
        migrations.AlterModelOptions(
            name='entityworkflow',
            options={'verbose_name': 'Entity Workflow Link (اتصال موجودیت)', 'verbose_name_plural': 'Entity Workflow Links (اتصالات موجودیت)'},
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'ordering': ('-created_at',), 'permissions': [('view_all_instances', 'مشاهده همه درخواست\u200cها'), ('approve_instance', 'تأیید درخواست'), ('cancel_any_instance', 'لغو هر درخواست')], 'verbose_name': 'Instance (نمونه فرآیند)', 'verbose_name_plural': 'Instances (نمونه\u200cهای فرآیند)'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('workflow_definition', 'code'), 'verbose_name': 'State (وضعیت)', 'verbose_name_plural': 'States (وضعیت\u200cها)'},
        ),
        migrations.AlterModelOptions(
            name='transition',
            options={'ordering': ('workflow_definition', 'from_state', 'to_state'), 'verbose_name': 'Transition (انتقال)', 'verbose_name_plural': 'Transitions (انتقال\u200cها)'},
        ),
        migrations.AlterModelOptions(
            name='workflowdefinition',
            options={'ordering': ('code', 'version'), 'permissions': [('manage_workflow_definition', 'مدیریت تعاریف فرآیند')], 'verbose_name': 'Workflow Definition (تعریف فرآیند)', 'verbose_name_plural': 'Workflow Definitions (تعاریف فرآیند)'},
        ),
        migrations.RemoveConstraint(
            model_name='entityworkflow',
            name='uniq_workflow_entity_link',
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(db_index=True, help_text='نام اقدام — create, submit, approve, reject, cancel', max_length=64),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='کامنت کاربر در زمان انجام اقدام'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='داده\u200cهای اضافی (مثلاً مقادیر فرم در زمان ثبت)'),
        ),
        migrations.AlterField(
            model_name='entityworkflow',
            name='object_id',
            field=models.UUIDField(db_index=True, help_text='PK موجودیت دامنه (UUID)'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='description',
            field=models.TextField(blank=True, default='', help_text='توضیحات تکمیلی درخواست'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('running', 'Running (در حال اجرا)'), ('completed', 'Completed (تکمیل)'), ('rejected', 'Rejected (رد شده)'), ('cancelled', 'Cancelled (لغو شده)')], db_index=True, default='running', max_length=32),
        ),
        migrations.AlterField(
            model_name='instance',
            name='title',
            field=models.CharField(help_text='عنوان درخواست — مثلاً «مرخصی ۳ روزه از ۱۵ تا ۱۷ مهر»', max_length=512),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.SlugField(help_text='شناسه وضعیت — مثلاً pending-manager, approved', max_length=64),
        ),
        migrations.AlterField(
            model_name='state',
            name='is_final',
            field=models.BooleanField(db_index=True, default=False, help_text='آیا این وضعیت پایان فرآیند است؟'),
        ),
        migrations.AlterField(
            model_name='state',
            name='is_initial',
            field=models.BooleanField(db_index=True, default=False, help_text='آیا این وضعیت شروع فرآیند است؟'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(help_text='نام نمایشی وضعیت — مثلاً «در انتظار تأیید مدیر»', max_length=256),
        ),
        migrations.AlterField(
            model_name='transition',
            name='allowed_role_codes',
            field=models.JSONField(blank=True, default=list, help_text='نقش\u200cهای مجاز برای انجام این انتقال. مثال: ["manager"], ["hr", "admin"].\nخالی = همه می\u200cتوانند (فقط با داشتن Instance و State مناسب).'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='guard_expression',
            field=models.JSONField(blank=True, default=dict, help_text='شرط پیشرفته برای این انتقال (JSON). مثال:\n{"type": "always_true"} — همیشه مجاز\n{"type": "field_not_equals", "field": "requester_id", "source": "actor.id"}\n    — مدیر نتواند درخواست خودش را تأیید کند\n{"type": "entity_field_lt", "field": "enrolled_count", "other_field": "capacity"}\n    — اگر ظرفیت پر است، اجازه تأیید نده\n{"type": "all", "guards": [...]} — همه زیرشرط\u200cها باید درست باشند\n{"type": "any", "guards": [...]} — حداقل یکی از زیرشرط\u200cها باید درست باشد\nخالی/{} = همیشه مجاز. نوع ناشناخته = مسدود (fail-closed).'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='name',
            field=models.CharField(help_text='نام اقدام — مثلاً submit, approve, reject', max_length=256),
        ),
        migrations.AlterField(
            model_name='transition',
            name='requires_comment',
            field=models.BooleanField(default=False, help_text='آیا کاربر حتماً باید کامنت وارد کند؟'),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='code',
            field=models.SlugField(help_text='Business key / شناسه یکتای فرآیند — مثلاً leave-request, grade-submission', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='name',
            field=models.CharField(help_text='نام نمایشی فرآیند — مثلاً «درخواست مرخصی»', max_length=256),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='نسخه — برای به\u200cروزرسانی تعریف بدون شکستن نمونه\u200cهای در حال اجرا'),
        ),
        migrations.AddConstraint(
            model_name='entityworkflow',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='uniq_workflow_entity_link', violation_error_message='این موجودیت قبلاً به یک Instance دیگر متصل شده است.'),
        ),
    ]
