# Generated by Django 5.1.15 on 2026-09-09 21:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_actionlog_options_alter_entityworkflow_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='default_due_hours',
            field=models.PositiveIntegerField(blank=True, help_text='مهلت پیش\u200cفرض تسک\u200cهای این وضعیت (ساعت). خالی = بدون مهلت.', null=True),
        ),
        migrations.AddField(
            model_name='transition',
            name='kind',
            field=models.CharField(blank=True, default='', help_text='نوع معنایی انتقال برای سرویس\u200cهای سطح\u200cبالاتر: approve, reject, return, complete, submit. خالی = سفارشی (فقط نام).', max_length=32),
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role_code', models.CharField(blank=True, default='', help_text='نقش موثر تاییدکننده در لحظه\u200cی تایید.', max_length=64)),
                ('unit', models.CharField(blank=True, default='', help_text='واحد/دپارتمان تاییدکننده (رشته آزاد تا مدل سازمان ساخته شود).', max_length=128)),
                ('action', models.CharField(help_text='approve / reject / return …', max_length=64)),
                ('comment', models.TextField(blank=True, default='')),
                ('is_revoked', models.BooleanField(db_index=True, default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_approvals', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflow.instance')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_approvals', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, help_text='وضعیتی که تایید در آن انجام شد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_records', to='workflow.state')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_records', to='workflow.transition')),
            ],
            options={
                'verbose_name': 'Approval Record (رکورد تایید)',
                'verbose_name_plural': 'Approval Records (رکوردهای تایید)',
                'db_table': 'workflow_approval_record',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['instance', 'created_at'], name='workflow_ap_instanc_080caa_idx'), models.Index(fields=['approver', 'created_at'], name='workflow_ap_approve_5e6b50_idx')],
            },
        ),
        migrations.CreateModel(
            name='InstanceCopy',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='workflow.instance')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_copies_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_copies_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instance Copy (رونوشت)',
                'verbose_name_plural': 'Instance Copies (رونوشت\u200cها)',
                'db_table': 'workflow_instance_copy',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='workflow_in_recipie_1dabfb_idx'), models.Index(fields=['instance', 'recipient'], name='workflow_in_instanc_21da28_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('in_app', 'درون\u200cبرنامه'), ('email', 'ایمیل'), ('sms', 'پیامک')], db_index=True, default='in_app', max_length=16)),
                ('template', models.CharField(blank=True, default='', help_text='کلید قالب اعلان — مثلاً task_created, approved, rejected.', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'در انتظار ارسال'), ('sent', 'ارسال\u200cشده'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflow.instance')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Outbox (صندوق خروجی اعلان)',
                'verbose_name_plural': 'Notification Outbox (اعلان\u200cهای خروجی)',
                'db_table': 'workflow_notification_outbox',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='workflow_no_status_e1e44d_idx'), models.Index(fields=['recipient', 'status'], name='workflow_no_recipie_d87474_idx')],
            },
        ),
    ]
