# Generated by Django 5.1.15 on 2026-09-10 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_state_default_due_hours_transition_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='کلید یکتای کلاینت برای جلوگیری از اجرای دوباره (double-click / retry). کلید تکراری => همان نتیجه\u200cی اول بازگردانده می\u200cشود نه خطا.', max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='actionlog',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='uniq_workflow_actionlog_idempotency_key'),
        ),
    ]
