# Generated by Django 5.1.15 on 2026-09-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_instance_subject_person'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='instance',
            new_name='workflow_in_subject_4e3363_idx',
            old_name='workflow_ins_subjec_idx',
        ),
    ]
