# Generated by Django 5.1.15 on 2026-09-24 03:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_rename_workflow_ins_subjec_idx_workflow_in_subject_4e3363_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notificationoutbox',
            name='workflow_no_status_e1e44d_idx',
        ),
        migrations.AddField(
            model_name='notificationoutbox',
            name='claimed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationoutbox',
            name='delivery_key',
            field=models.CharField(blank=True, help_text='کلید تکرارنشدن رخداد؛ null برای داده\u200cهای قدیمی.', max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notificationoutbox',
            name='next_attempt_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_logs', to='workflow.instance'),
        ),
        migrations.AlterField(
            model_name='approvalrecord',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='workflow.instance'),
        ),
        migrations.AlterField(
            model_name='notificationoutbox',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار ارسال'), ('processing', 'در حال ارسال'), ('sent', 'ارسال\u200cشده'), ('failed', 'ناموفق'), ('dead_letter', 'صف مرده')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddIndex(
            model_name='notificationoutbox',
            index=models.Index(fields=['status', 'next_attempt_at'], name='workflow_no_status_f0341a_idx'),
        ),
    ]
