# Generated by Django 5.1.15 on 2026-09-24 03:42

from django.db import migrations, models


def move_legacy_failures_to_dead_letter(apps, schema_editor):
    Outbox = apps.get_model("workflow", "NotificationOutbox")
    Outbox.objects.using(schema_editor.connection.alias).filter(
        status="failed",
    ).update(status="dead_letter")


def restore_legacy_failures(apps, schema_editor):
    Outbox = apps.get_model("workflow", "NotificationOutbox")
    Outbox.objects.using(schema_editor.connection.alias).filter(
        status="dead_letter",
    ).update(status="failed")


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow', '0011_remove_notificationoutbox_workflow_no_status_e1e44d_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(
            move_legacy_failures_to_dead_letter,
            restore_legacy_failures,
        ),
        migrations.RemoveConstraint(
            model_name='entityworkflow',
            name='uniq_workflow_entity_link',
        ),
        migrations.AlterField(
            model_name='notificationoutbox',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار ارسال'), ('processing', 'در حال ارسال'), ('sent', 'ارسال\u200cشده'), ('dead_letter', 'صف مرده')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='code',
            field=models.SlugField(help_text='Business key / شناسه یکتای فرآیند — مثلاً leave-request, grade-submission', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='entityworkflow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('content_type', 'object_id'), name='uniq_workflow_entity_link', violation_error_message='این موجودیت قبلاً به یک Instance دیگر متصل شده است.'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_initial', True)), fields=('workflow_definition',), name='uniq_workflow_initial_state'),
        ),
        migrations.AddConstraint(
            model_name='transition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('workflow_definition', 'from_state', 'name'), name='uniq_workflow_transition_route_name'),
        ),
        migrations.AddConstraint(
            model_name='transition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('kind', ''), _negated=True)), fields=('workflow_definition', 'from_state', 'kind'), name='uniq_workflow_transition_route_kind'),
        ),
        migrations.AddConstraint(
            model_name='workflowdefinition',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='uniq_workflow_code_version'),
        ),
        migrations.AddConstraint(
            model_name='workflowdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('code',), name='uniq_active_workflow_code'),
        ),
    ]
