# Generated by Django 5.1.15 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0012_remove_entityworkflow_uniq_workflow_entity_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="assignment_policy",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    'سیاست تخصیص تسک به‌صورت JSON. مثال: '
                    '{"strategy": "direct_manager", "fallback_roles": ["manager"]}. '
                    "خالی = رفتار سازگار با گردش‌کارهای قدیمی."
                ),
            ),
        ),
    ]
