"""
Education URL configuration — mounted under /api/education/ in pen/urls.py.
"""
from __future__ import annotations

from django.urls import path

from apps.education.calendar_views import (
    MyCalendarView,
    ResourceCalendarView,
)
from apps.education.timetable_views import TimetableView
from apps.education.views import (
    AttendanceReportView,
    CapacityReportView,
    ClassFormationPreviewView,
    ClassFormationView,
    HolidayDetailView,
    HolidayListCreateView,
    HolidayRestoreView,
    HolidaySoftDeleteView,
    CourseDetailView,
    CourseListCreateView,
    CourseRestoreView,
    CourseSoftDeleteView,
    DepartmentDetailView,
    DepartmentListCreateView,
    DepartmentRestoreView,
    DepartmentSoftDeleteView,
    EnrollmentRestoreView,
    EnrollmentSoftDeleteView,
    LessonDetailView,
    LessonListCreateView,
    LessonRestoreView,
    LessonSoftDeleteView,
    LocationDetailView,
    LocationListCreateView,
    LocationRestoreView,
    LocationSoftDeleteView,
    OfferingDetailView,
    OfferingRestoreView,
    OfferingSoftDeleteView,
    OfferingEnrollView,
    OfferingEnrollmentDetailView,
    OfferingEnrollmentListCreateView,
    OfferingFormationView,
    OfferingGenerateSessionsView,
    OfferingListCreateView,
    OfferingCreateSessionView,
    LearnerReportCardDeliveryView,
    OfferingReportCardsView,
    OfferingRecordSessionView,
    OfferingRosterView,
    OfferingSessionSheetView,
    SessionMaterialDetailView,
    SessionMaterialListCreateView,
    LearnerPortalView,
    TeacherClassesView,
    SessionAttendanceListView,
    SessionBulkAttendanceView,
    SessionDetailView,
    SessionListCreateView,
    SessionRestoreView,
    SessionSoftDeleteView,
    WaitlistListCreateView,
    WaitlistOfferView,
)

urlpatterns = [
    path("departments/", DepartmentListCreateView.as_view(), name="edu-department-list"),
    path("departments/<uuid:pk>/", DepartmentDetailView.as_view(), name="edu-department-detail"),
    path("departments/<uuid:pk>/delete/", DepartmentSoftDeleteView.as_view(), name="edu-department-delete"),
    path("departments/<uuid:pk>/restore/", DepartmentRestoreView.as_view(), name="edu-department-restore"),
    path("locations/", LocationListCreateView.as_view(), name="edu-location-list"),
    path("locations/<uuid:pk>/", LocationDetailView.as_view(), name="edu-location-detail"),
    path("locations/<uuid:pk>/delete/", LocationSoftDeleteView.as_view(), name="edu-location-delete"),
    path("locations/<uuid:pk>/restore/", LocationRestoreView.as_view(), name="edu-location-restore"),
    path("lessons/", LessonListCreateView.as_view(), name="edu-lesson-list"),
    path("lessons/<uuid:pk>/", LessonDetailView.as_view(), name="edu-lesson-detail"),
    path("lessons/<uuid:pk>/delete/", LessonSoftDeleteView.as_view(), name="edu-lesson-delete"),
    path("lessons/<uuid:pk>/restore/", LessonRestoreView.as_view(), name="edu-lesson-restore"),
    path("courses/", CourseListCreateView.as_view(), name="edu-course-list"),
    path("courses/<uuid:pk>/", CourseDetailView.as_view(), name="edu-course-detail"),
    path("courses/<uuid:pk>/delete/", CourseSoftDeleteView.as_view(), name="edu-course-delete"),
    path("courses/<uuid:pk>/restore/", CourseRestoreView.as_view(), name="edu-course-restore"),
    path("offerings/", OfferingListCreateView.as_view(), name="edu-offering-list"),
    path("offerings/<uuid:pk>/", OfferingDetailView.as_view(), name="edu-offering-detail"),
    path("offerings/<uuid:pk>/delete/", OfferingSoftDeleteView.as_view(), name="edu-offering-delete"),
    path("offerings/<uuid:pk>/restore/", OfferingRestoreView.as_view(), name="edu-offering-restore"),
    path("offerings/<uuid:pk>/enroll/", OfferingEnrollView.as_view(), name="edu-offering-enroll"),
    path("offerings/<uuid:pk>/waitlist/offer-next/", WaitlistOfferView.as_view(), name="edu-waitlist-offer-next"),
    path("offerings/<uuid:pk>/generate-sessions/", OfferingGenerateSessionsView.as_view(), name="edu-offering-generate-sessions"),
    # «تشکیل کلاس»: read-model → dry-run preview → atomic generation
    path("offerings/<uuid:pk>/formation/", OfferingFormationView.as_view(), name="edu-offering-formation"),
    path("class-formation/", ClassFormationView.as_view(), name="edu-class-formation"),
    path("class-formation/preview/", ClassFormationPreviewView.as_view(), name="edu-class-formation-preview"),
    path("enrollments/", OfferingEnrollmentListCreateView.as_view(), name="edu-enrollment-list"),
    path("enrollments/<uuid:pk>/", OfferingEnrollmentDetailView.as_view(), name="edu-enrollment-detail"),
    path("enrollments/<uuid:pk>/delete/", EnrollmentSoftDeleteView.as_view(), name="edu-enrollment-delete"),
    path("enrollments/<uuid:pk>/restore/", EnrollmentRestoreView.as_view(), name="edu-enrollment-restore"),
    path("waitlist/", WaitlistListCreateView.as_view(), name="edu-waitlist-list"),
    path("sessions/", SessionListCreateView.as_view(), name="edu-session-list"),
    path("sessions/<uuid:pk>/", SessionDetailView.as_view(), name="edu-session-detail"),
    path("sessions/<uuid:pk>/delete/", SessionSoftDeleteView.as_view(), name="edu-session-delete"),
    path("sessions/<uuid:pk>/restore/", SessionRestoreView.as_view(), name="edu-session-restore"),
    path("sessions/<uuid:pk>/attendance/",
         SessionBulkAttendanceView.as_view(), name="edu-session-attendance-post"),
    path("sessions/<uuid:pk>/roster/",
         SessionAttendanceListView.as_view(), name="edu-session-roster"),
    path("sessions/<uuid:pk>/materials/", SessionMaterialListCreateView.as_view(), name="edu-session-materials"),
    path("materials/<uuid:pk>/delete/", SessionMaterialDetailView.as_view(), name="edu-session-material-delete"),
    # Teacher portal + learner portal
    path("teacher/classes/", TeacherClassesView.as_view(), name="edu-teacher-classes"),
    path("offerings/<uuid:pk>/roster/", OfferingRosterView.as_view(), name="edu-offering-roster"),
    path("offerings/<uuid:pk>/sessions/", OfferingCreateSessionView.as_view(), name="edu-offering-create-session"),
    path("offerings/<uuid:pk>/record-session/", OfferingRecordSessionView.as_view(), name="edu-offering-record-session"),
    path("offerings/<uuid:pk>/sheet/", OfferingSessionSheetView.as_view(), name="edu-offering-sheet"),
    path("offerings/<uuid:pk>/report-cards/", OfferingReportCardsView.as_view(), name="edu-offering-report-cards"),
    path("portal/", LearnerPortalView.as_view(), name="edu-learner-portal"),
    path("portal/report-card/", LearnerReportCardDeliveryView.as_view(), name="edu-learner-report-card-delivery"),
    # Reports (§13-7)
    path("reports/attendance/", AttendanceReportView.as_view(), name="edu-report-attendance"),
    path("reports/capacity/", CapacityReportView.as_view(), name="edu-report-capacity"),

    # Daily timetable (read model for the UI grid)
    path("timetable/", TimetableView.as_view(), name="edu-timetable"),

    # Role-based calendars: staff → resource/room master view; every signed-in
    # user → their own schedule via the selector matching their role
    # (teacher: classes they teach; student: only confirmed enrollments;
    # guardian: their wards' sessions — all enforced inside the selectors).
    path("calendar/resources/", ResourceCalendarView.as_view(), name="edu-calendar-resources"),
    path("calendar/me/", MyCalendarView.as_view(), name="edu-calendar-me"),

    # Holiday calendar (single source of truth for session skipping)
    path("holidays/", HolidayListCreateView.as_view(), name="edu-holiday-list"),
    path("holidays/<uuid:pk>/", HolidayDetailView.as_view(), name="edu-holiday-detail"),
    path("holidays/<uuid:pk>/delete/", HolidaySoftDeleteView.as_view(), name="edu-holiday-delete"),
    path("holidays/<uuid:pk>/restore/", HolidayRestoreView.as_view(), name="edu-holiday-restore"),
]
