# Generated by Django 5.1.15 on 2026-09-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='formattachment',
            new_name='forms_attac_submiss_7981b1_idx',
            old_name='forms_attach_sub_field_idx',
        ),
        migrations.RenameIndex(
            model_name='formcomment',
            new_name='forms_comme_submiss_dcd07a_idx',
            old_name='forms_comment_sub_created_idx',
        ),
        migrations.RenameIndex(
            model_name='formschema',
            new_name='forms_schem_slug_08a394_idx',
            old_name='forms_schema_slug_active_idx',
        ),
        migrations.RenameIndex(
            model_name='formschema',
            new_name='forms_schem_workflo_86e2ec_idx',
            old_name='forms_schema_workflow_idx',
        ),
        migrations.RenameIndex(
            model_name='formsubmission',
            new_name='forms_submi_form_sc_f66e92_idx',
            old_name='forms_sub_schema_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='formsubmission',
            new_name='forms_submi_status_f760e6_idx',
            old_name='forms_sub_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='formsubmission',
            new_name='forms_submi_submitt_6d0094_idx',
            old_name='forms_sub_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='formsubmission',
            new_name='forms_submi_form_sc_154b0c_idx',
            old_name='forms_sub_schema_created_idx',
        ),
        migrations.RenameIndex(
            model_name='formsubmission',
            new_name='forms_submi_class_g_35585c_idx',
            old_name='forms_sub_class_group_idx',
        ),
        migrations.RenameIndex(
            model_name='formsubmission',
            new_name='forms_submi_subject_abae16_idx',
            old_name='forms_sub_subject_person_idx',
        ),
        migrations.RenameIndex(
            model_name='submissionsequence',
            new_name='forms_submi_slug_028c9c_idx',
            old_name='forms_seq_slug_year_idx',
        ),
    ]
