# Generated by Django 5.1.15 on 2026-09-24 04:01

from django.db import migrations, models
from django.utils import timezone


def queue_existing_attendance_submissions(apps, schema_editor):
    FormSubmission = apps.get_model("forms", "FormSubmission")
    FormSubmission.objects.using(schema_editor.connection.alias).filter(
        form_schema__slug="attendance",
        submitted_at__isnull=False,
    ).update(
        projection_status="pending",
        projection_next_attempt_at=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_subnum_nullable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='projection_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='projection_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='projection_next_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='projection_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='not_applicable', max_length=20),
        ),
        migrations.RunPython(queue_existing_attendance_submissions, migrations.RunPython.noop),
    ]
