# Generated by Django 5.1.15 on 2026-09-27 14:36

import django.db.models.deletion
import apps.forms.models
from django.conf import settings
from django.db import migrations, models


def backfill_form_first_fields(apps, schema_editor):
    FormSchema = apps.get_model("forms", "FormSchema")
    FormSubmission = apps.get_model("forms", "FormSubmission")
    Request = apps.get_model("forms", "Request")
    db = schema_editor.connection.alias
    category_by_slug = {
        "person": "persons", "persons": "persons", "personnel": "persons",
        "department": "departments", "departments": "departments",
        "lesson": "courses", "course": "courses", "course-offering": "classes",
        "class-session-setup": "classes", "attendance": "classes",
        "grade-report": "classes", "message": "messages", "messages": "messages",
    }
    for schema in FormSchema.objects.using(db).all().iterator():
        workflow = schema.workflow_definition
        if schema.request_type_id:
            request_type = schema.request_type
            workflow = request_type.workflow_definition or workflow
        roles = list(schema.allowed_roles.values_list("code", flat=True))
        schema.category = category_by_slug.get(schema.slug, "general")
        schema.workflow_config = {
            "execution_mode": "workflow" if workflow else "direct",
            "allow_on_behalf": False,
            "eligible_initiator_roles": roles,
            "routing_rules": [],
        }
        schema.save(update_fields=["category", "workflow_config"])

    for submission in FormSubmission.objects.using(db).select_related(
        "form_schema", "subject_person"
    ).iterator():
        snapshot = {
            "slug": submission.form_schema.slug,
            "title": submission.form_schema.title,
            "version": submission.schema_version_snapshot or submission.form_schema.version,
            "category": submission.form_schema.category,
            "description": submission.form_schema.description,
            "fields": submission.version_snapshot.get("fields")
            if isinstance(submission.version_snapshot, dict) and submission.version_snapshot.get("fields")
            else submission.form_schema.fields,
            "workflow_config": submission.form_schema.workflow_config,
            "metadata": submission.form_schema.metadata,
        }
        subject_user_id = getattr(submission.subject_person, "user_id", None)
        FormSubmission.objects.using(db).filter(pk=submission.pk).update(
            initiator_id=submission.submitted_by_id,
            subject_user_id=subject_user_id or submission.submitted_by_id,
            schema_snapshot=snapshot,
        )
        Request.objects.using(db).filter(form_submission_id=submission.pk).update(
            initiator_id=submission.submitted_by_id,
            subject_user_id=subject_user_id or submission.submitted_by_id,
            is_on_behalf=False,
            schema_snapshot=snapshot,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_unified_request_layer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formschema',
            name='category',
            field=models.CharField(choices=[('persons', 'افراد'), ('departments', 'دپارتمان\u200cها'), ('courses', 'درس\u200cها و دوره\u200cها'), ('classes', 'برگزاری\u200cها و کلاس\u200cها'), ('messages', 'پیام\u200cها'), ('general', 'سایر خدمات')], db_index=True, default='general', max_length=24),
        ),
        migrations.AddField(
            model_name='formschema',
            name='workflow_config',
            field=models.JSONField(blank=True, default=apps.forms.models.default_workflow_config, help_text='تنظیمات اجرای فرم: execution_mode, allow_on_behalf, eligible_initiator_roles و routing_rules.'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiated_form_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='is_on_behalf',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='schema_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot تغییرناپذیر schema و تنظیمات اجرا در زمان ثبت.'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='subject_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_form_submissions_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiated_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='is_on_behalf',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='schema_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='request',
            name='subject_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_form_first_fields, migrations.RunPython.noop),
    ]
