# Generated by Django 5.1.15 on 2026-09-12 10:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.CharField(blank=True, default='', help_text='واحد/دپارتمان مشمول (خالی = کل کارتابل).', max_length=128)),
                ('workflow_code', models.SlugField(blank=True, default='', help_text='اگر فقط یک فرآیند خاص مد نظر است (مثلاً leave-request).', max_length=64)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delegations', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(help_text='جانشین.', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(help_text='کسی که کارش به دیگری سپرده می\u200cشود (صاحب اصلی کارتابل).', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_delegations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delegation (جانشینی)',
                'verbose_name_plural': 'Delegations (جانشینی\u200cها)',
                'db_table': 'org_delegation',
                'ordering': ('-valid_from',),
                'indexes': [models.Index(fields=['principal', 'is_active'], name='org_delegat_princip_1ef898_idx'), models.Index(fields=['delegate', 'is_active'], name='org_delegat_delegat_8996d8_idx')],
            },
        ),
    ]
