# Generated by Django 5.x — add_person_acl_entry
# Person ACL: explicit per-user per-resource per-verb grants.
# Run on your PostgreSQL machine: python manage.py migrate

import django.utils.timezone
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonACLEntry",
            fields=[
                # DomainModel fields (UUID PK + timestamps + soft delete)
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                # Core fields
                (
                    "user",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_acl_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("page", "صفحه (workspace)"), ("form", "فرم داینامیک"), ("model", "ماژول / Model")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("resource_key", models.CharField(db_index=True, max_length=120)),
                (
                    "verbs",
                    models.JSONField(
                        default=list,
                        help_text="لیست ACLVerb — مثل [\"view\",\"add\"]",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="چه کسی این دسترسی صریح را داده (audit).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_acl_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_acl_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Person ACL Entry (دسترسی صریح)",
                "verbose_name_plural": "Person ACL Entries (دسترسی‌های صریح)",
                "db_table": "org_person_acl_entry",
                "ordering": ("resource_type", "resource_key"),
            },
        ),
        # Partial unique constraint — one live row per (user, type, key)
        # Postgres creates a supporting index for UniqueConstraint automatically.
        migrations.AddConstraint(
            model_name="personaclentry",
            constraint=models.UniqueConstraint(
                fields=["user", "resource_type", "resource_key"],
                condition=models.Q(is_deleted=False),
                name="uniq_org_person_acl_live",
            ),
        ),
    ]