# Generated by Django 5.1.15 on 2026-09-25 13:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_add_personaclentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarVisibilityRule',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('item_key', models.CharField(db_index=True, max_length=120)),
                ('is_visible', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sidebar_visibility_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sidebar visibility rule (قانون نمایش سایدبار)',
                'verbose_name_plural': 'Sidebar visibility rules (قوانین نمایش سایدبار)',
                'db_table': 'org_sidebar_visibility_rule',
                'ordering': ('role_code', 'item_key'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('user__isnull', True)), fields=('role_code', 'item_key'), name='uniq_org_sidebar_role_item_live'), models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('user__isnull', False)), fields=('user', 'item_key'), name='uniq_org_sidebar_user_item_live'), models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', True), models.Q(('role_code', ''), _negated=True)), models.Q(('role_code', ''), ('user__isnull', False)), _connector='OR'), name='org_sidebar_visibility_scope_valid')],
            },
        ),
    ]
