# Generated by Django 5.1.15 on 2026-09-26 01:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
        ('persons', '0009_alter_guardianprofile_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='callfollowuplog',
            new_name='calls_follo_actor_i_54f537_idx',
            old_name='calls_log_actor_created_idx',
        ),
        migrations.AlterField(
            model_name='inboundcall',
            name='caller_phone',
            field=models.CharField(db_index=True, help_text='شماره تماس گیرنده — پیش\u200cشماره و اعداد لاتین.', max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()]{3,20}$', 'شماره تلفن معتبر نیست.')]),
        ),
        migrations.AlterField(
            model_name='inboundcall',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='inboundcall',
            name='person',
            field=models.ForeignKey(blank=True, help_text='اگر تماس\u200cگیرنده شخص ثبت\u200cشده است، هویت اینجا وصل می\u200cشود (تکرار هویت ممنوع).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_calls', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='inboundcall',
            name='subject',
            field=models.CharField(db_index=True, help_text='موضوع تماس — متن کوتاه قابل فیلتر (مثلاً «استعلام شهریه»، «ثبت\u200cنام»، «غیبت»).', max_length=256),
        ),
    ]
