# Generated by Django 5.1.15 on 2026-09-09 21:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_remove_classenrollment_uniq_academics_enrollment_and_more'),
        ('persons', '0004_remove_studentparent_uniq_persons_student_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=256)),
                ('code', models.SlugField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('objectives', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('legacy_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Course (دوره)',
                'verbose_name_plural': 'Courses (دوره\u200cها)',
                'db_table': 'education_course',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='۰ = نامحدود')),
                ('enrolled_count', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('open', 'باز (ثبت\u200cنام)'), ('closed', 'بسته'), ('running', 'در حال برگزاری'), ('finished', 'پایان\u200cیافته'), ('cancelled', 'لغوشده')], db_index=True, default='draft', max_length=16)),
                ('tuition', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('legacy_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='education.course')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'person_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_courses', to='persons.person')),
            ],
            options={
                'verbose_name': 'Course Offering (برگزاری دوره)',
                'verbose_name_plural': 'Course Offerings (برگزاری\u200cهای دوره)',
                'db_table': 'education_course_offering',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('session_number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('session_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'برنامه\u200cریزی\u200cشده'), ('held', 'برگزارشده'), ('cancelled', 'لغوشده')], db_index=True, default='scheduled', max_length=16)),
                ('legacy_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('class_group', models.ForeignKey(blank=True, help_text='پل بین جلسه\u200cی واقعی و گروه کلاسی academics (گزارش روزانه / فرم حضور)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='academics.classgroup')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'person_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_sessions', to='persons.person')),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='education.courseoffering')),
            ],
            options={
                'verbose_name': 'Class Session (جلسه)',
                'verbose_name_plural': 'Class Sessions (جلسات)',
                'db_table': 'education_class_session',
                'ordering': ('session_date', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('legacy_id', models.CharField(blank=True, db_index=True, default='', help_text='شناسه در سیستم قدیمی (ASP) برای مهاجرت و تطبیق.', max_length=64)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='education.department')),
            ],
            options={
                'verbose_name': 'Department (واحد آموزشی)',
                'verbose_name_plural': 'Departments (واحدهای آموزشی)',
                'db_table': 'education_department',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='education.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='education.department'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=256)),
                ('code', models.SlugField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('syllabus', models.TextField(blank=True, default='', help_text='سرفصل/مباحث')),
                ('duration_hours', models.PositiveIntegerField(default=0)),
                ('assessment_method', models.CharField(blank=True, default='', help_text='written/oral/project/none', max_length=32)),
                ('required_equipment', models.TextField(blank=True, default='')),
                ('learning_resources', models.TextField(blank=True, default='')),
                ('tuition', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('legacy_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='education.department')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='prerequisite_of', to='education.lesson')),
            ],
            options={
                'verbose_name': 'Lesson (درس)',
                'verbose_name_plural': 'Lessons (درس\u200cها)',
                'db_table': 'education_lesson',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(choices=[('passed', 'قبول'), ('failed', 'مردود')], db_index=True, default='passed', max_length=16)),
                ('teacher_note', models.CharField(help_text='یادداشت توصیفی مدرس — برای مردود اجباری است.', max_length=1000)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_grades', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='education.courseoffering')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='education.classsession')),
                ('student', models.ForeignKey(limit_choices_to={'person_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='persons.person')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='education.lesson')),
            ],
            options={
                'verbose_name': 'Grade Record (ارزیابی)',
                'verbose_name_plural': 'Grade Records (ارزیابی\u200cها)',
                'db_table': 'education_grade_record',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('required', models.BooleanField(default=True)),
                ('hours', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lessons', to='education.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_links', to='education.lesson')),
            ],
            options={
                'verbose_name': 'Course Lesson (درس دوره)',
                'verbose_name_plural': 'Course Lessons (درس\u200cهای دوره)',
                'db_table': 'education_course_lesson',
                'ordering': ('course', 'order'),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='courses', through='education.CourseLesson', to='education.lesson'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='education.lesson'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(blank=True, max_length=64)),
                ('building', models.CharField(blank=True, default='', max_length=200)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='۰ = نامحدود')),
                ('equipment', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('legacy_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Location (فضای آموزشی)',
                'verbose_name_plural': 'Locations (فضاهای آموزشی)',
                'db_table': 'education_location',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('code', ''), _negated=True)), fields=('code',), name='uniq_edu_location_code_alive')],
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='education.location'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='education.location'),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب'), ('late', 'تأخیر'), ('excused', 'موجه')], db_index=True, default='present', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'person_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='persons.person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='education.classsession')),
            ],
            options={
                'verbose_name': 'Attendance Record (حضور)',
                'verbose_name_plural': 'Attendance Records (حضور و غیاب)',
                'db_table': 'education_attendance_record',
                'ordering': ('session', 'student'),
                'indexes': [models.Index(fields=['student', 'status'], name='education_a_student_c12622_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('session', 'student'), name='uniq_edu_attendance_session_student_alive', violation_error_message='حضور این دانش\u200cآموز برای این جلسه قبلاً ثبت شده است.')],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_edu_department_code_alive'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_edu_lesson_code_alive'),
        ),
        migrations.AddConstraint(
            model_name='graderecord',
            constraint=models.CheckConstraint(condition=models.Q(('session__isnull', False), ('offering__isnull', False), _connector='OR'), name='chk_edu_grade_has_target'),
        ),
        migrations.AddConstraint(
            model_name='graderecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student', 'session', 'lesson'), name='uniq_edu_grade_session_alive'),
        ),
        migrations.AddConstraint(
            model_name='graderecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('session__isnull', True)), fields=('student', 'offering'), name='uniq_edu_grade_offering_final_alive'),
        ),
        migrations.AddConstraint(
            model_name='courselesson',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('course', 'lesson'), name='uniq_edu_course_lesson_alive'),
        ),
        migrations.AddConstraint(
            model_name='courselesson',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('course', 'order'), name='uniq_edu_course_lesson_order_alive'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_edu_course_code_alive'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['course', 'status'], name='education_c_course__d3ec3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='chk_edu_offering_dates'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.CheckConstraint(condition=models.Q(('enrolled_count__lte', models.F('capacity')), ('capacity', 0), _connector='OR'), name='chk_edu_offering_capacity'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['session_date', 'status'], name='education_c_session_693639_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['teacher', 'session_date'], name='education_c_teacher_4f5738_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['location', 'session_date'], name='education_c_locatio_4bf932_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['class_group', 'session_date'], name='education_c_class_g_0a6679_idx'),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='chk_edu_session_time_window'),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.CheckConstraint(condition=models.Q(('offering__isnull', False), ('class_group__isnull', False), _connector='OR'), name='chk_edu_session_target'),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('offering__isnull', False)), fields=('offering', 'session_number'), name='uniq_edu_session_number_alive'),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('class_group__isnull', False)), fields=('class_group', 'session_date', 'session_number'), name='uniq_edu_session_group_date_number_alive'),
        ),
    ]
