# Generated by Django 5.1.15 on 2026-09-14 01:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('persons', '0005_persontypeassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tuition',
            field=models.PositiveIntegerField(default=0, help_text='شهریه دوره به تومان'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='schedule',
            field=models.JSONField(blank=True, default=dict, help_text='زمان برگزاری پیشنهادی: {days: ["sat","wed"], start: "18:00", end: "20:00"}'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audience_age_max',
            field=models.PositiveSmallIntegerField(blank=True, help_text='بیشینهٔ رنج سنی مخاطبان', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audience_age_min',
            field=models.PositiveSmallIntegerField(blank=True, help_text='کمینهٔ رنج سنی مخاطبان', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='space_type',
            field=models.CharField(blank=True, choices=[('', 'نامشخص'), ('classroom', 'کلاس'), ('lab', 'آزمایشگاه'), ('workshop', 'کارگاه'), ('online', 'آنلاین'), ('hall', 'سالن')], default='', help_text='نوع فضای آموزشی پیشنهادی', max_length=16),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='عنوان انگلیسی درس', max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.SlugField(help_text='کد دوره — خودکار cs-0001', max_length=64),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='code',
            field=models.SlugField(help_text='کد درس — خودکار ls-0001', max_length=64),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='عنوان فارسی درس', max_length=256),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tuition',
            field=models.PositiveIntegerField(default=0, help_text='شهریه به تومان'),
        ),
        migrations.CreateModel(
            name='OfferingEnrollment',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('course_amount', models.PositiveIntegerField(default=0, help_text='مبلغ دوره (تومان)')),
                ('discount_type', models.CharField(choices=[('none', 'بدون تخفیف'), ('percent', 'درصدی'), ('amount', 'مبلغ ثابت')], default='none', max_length=10)),
                ('discount_value', models.PositiveIntegerField(default=0, help_text='درصد (۰..۱۰۰) یا مبلغ تومان، بسته به نوع')),
                ('final_amount', models.PositiveIntegerField(default=0, help_text='مبلغ قابل\u200cپرداخت پس از تخفیف (تومان)')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('pos', 'کارت\u200cخوان (POS)'), ('cheque', 'چک')], default='cash', max_length=10)),
                ('cheque_count', models.PositiveSmallIntegerField(default=0)),
                ('cheques', models.JSONField(blank=True, default=list, help_text='فهرست چک\u200cها: [{amount, payee, due_date, tracking_no}]')),
                ('reference', models.CharField(blank=True, default='', help_text='کد پیگیری/رسید پرداخت (نقدی/پوز).', max_length=128)),
                ('enrolled_at', models.DateField(default=django.utils.timezone.localdate)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='education.courseoffering')),
                ('student', models.ForeignKey(limit_choices_to={'person_type': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='offerings_enrolled', to='persons.person')),
            ],
            options={
                'verbose_name': 'Offering Enrollment (ثبت\u200cنام)',
                'verbose_name_plural': 'Offering Enrollments (ثبت\u200cنام\u200cها)',
                'db_table': 'education_offering_enrollment',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['student', 'is_active'], name='education_o_student_97b3e4_idx'), models.Index(fields=['offering', 'is_active'], name='education_o_offerin_f3d92c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('offering', 'student'), name='uniq_edu_offering_enrollment_alive', violation_error_message='این دانش\u200cآموز قبلاً در این برگزاری ثبت\u200cنام کرده است.')],
            },
        ),
    ]
