# Generated by Django 5.1.15 on 2026-09-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_course_tuition_courseoffering_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='assessment_method',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='audience_age_max',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='audience_age_min',
        ),
        migrations.AddField(
            model_name='lesson',
            name='audience_age',
            field=models.CharField(blank=True, default='', help_text='محدوده سنی مخاطبان — مثال: 10-15', max_length=32),
        ),
    ]
