# Generated by Django 5.1.15 on 2026-09-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_offering_code_class_code'),
        ('persons', '0007_guardian_profiles'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseoffering',
            name='uniq_edu_offering_code_alive',
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('code', ''), _negated=True)), fields=('code',), name='uniq_edu_offering_code_alive'),
        ),
    ]
