# Generated by Django 5.1.15 on 2026-09-17 14:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_remove_courseoffering_uniq_edu_offering_code_alive_and_more'),
        ('persons', '0008_person_search_and_student_parents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='topic',
            field=models.CharField(blank=True, default='', help_text='موضوع درس این جلسه — برای برنامه\u200cریزی مدرس و مشاهدهٔ دانش\u200cآموز.', max_length=500),
        ),
        migrations.CreateModel(
            name='EnrollmentWaitlist',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'در صف انتظار'), ('offered', 'صندلی آزاد شد'), ('enrolled', 'به ثبت\u200cنام تبدیل شد'), ('declined', 'ردشده'), ('cancelled', 'لغوشده')], db_index=True, default='waiting', max_length=16)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('offered_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='education.courseoffering')),
                ('student', models.ForeignKey(limit_choices_to={'person_type': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_waitlists', to='persons.person')),
            ],
            options={
                'db_table': 'education_enrollment_waitlist',
                'ordering': ('requested_at', 'created_at'),
                'indexes': [models.Index(fields=['offering', 'status', 'requested_at'], name='education_e_offerin_6cc194_idx'), models.Index(fields=['student', 'status'], name='education_e_student_7d4638_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status__in', ['waiting', 'offered'])), fields=('offering', 'student'), name='uniq_edu_waitlist_active_student')],
            },
        ),
        migrations.CreateModel(
            name='ParentReportDelivery',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('pdf', 'PDF'), ('sms', 'پیامک')], db_index=True, max_length=8)),
                ('status', models.CharField(choices=[('queued', 'در صف ارسال'), ('sent', 'ارسال\u200cشده'), ('failed', 'ناموفق')], db_index=True, default='queued', max_length=16)),
                ('recipient', models.CharField(blank=True, default='', max_length=128)),
                ('period_label', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_parent_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_deliveries', to='persons.person')),
            ],
            options={
                'db_table': 'education_parent_report_delivery',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['student', 'channel', 'created_at'], name='education_p_student_57dc5b_idx'), models.Index(fields=['status', 'channel'], name='education_p_status_4e30e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionMaterial',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=256)),
                ('kind', models.CharField(choices=[('link', 'پیوند آموزشی'), ('file', 'فایل'), ('video', 'ویدئو')], default='link', max_length=16)),
                ('url', models.URLField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='education/session-materials/')),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='education.classsession')),
            ],
            options={
                'db_table': 'education_session_material',
                'ordering': ('sort_order', 'created_at'),
                'indexes': [models.Index(fields=['session', 'is_visible'], name='education_s_session_73e7b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionScheduleRevision',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_schedule_changes', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_revisions', to='education.classsession')),
            ],
            options={
                'db_table': 'education_session_schedule_revision',
                'ordering': ('-version', '-created_at'),
                'indexes': [models.Index(fields=['session', '-version'], name='education_s_session_63ed57_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('session', 'version'), name='uniq_edu_session_schedule_revision_alive')],
            },
        ),
    ]
