# Generated by Django 5.1.15 on 2026-09-24

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0004_remove_classenrollment_uniq_academics_enrollment_and_more",
        ),
        ("education", "0007_classsession_topic_enrollmentwaitlist_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="offeringenrollment",
            name="final_class_enrollment",
            field=models.OneToOneField(
                blank=True,
                help_text="عضویت قطعی در کلاس که پس از تشکیل کلاس ایجاد می‌شود.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_offering_enrollment",
                to="academics.classenrollment",
            ),
        ),
        migrations.AddField(
            model_name="offeringenrollment",
            name="lifecycle_status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار تأیید"),
                    ("confirmed", "تأییدشده"),
                    ("cancelled", "لغوشده"),
                    ("partially_refunded", "عودت جزئی"),
                    ("refunded", "عودت کامل"),
                ],
                db_index=True,
                default="confirmed",
                help_text="وضعیت چرخهٔ ثبت‌نام مستقل از وضعیت عضویت نهایی در کلاس.",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="EnrollmentRefund",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.PositiveIntegerField(help_text="مبلغ عودت به تومان")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "درخواست‌شده"),
                            ("approved", "تأییدشده"),
                            ("processed", "پردازش‌شده"),
                            ("rejected", "ردشده"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("reference", models.CharField(blank=True, default="", max_length=128)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="education.offeringenrollment",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_enrollment_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_enrollment_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "education_enrollment_refund",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["enrollment", "status"],
                        name="edu_refund_enroll_status_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="edu_refund_status_created_idx",
                    ),
                ],
            },
        ),
    ]
