# Generated by Django 5.1.15 on 2026-09-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_offeringenrollment_final_class_enrollment_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='offeringenrollment',
            index=models.Index(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=['offering', 'enrolled_at'], name='edu_enroll_report_idx'),
        ),
    ]
