# Generated by Django 5.1.15 on 2026-09-29 15:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_enrollment_report_index'),
        ('persons', '0009_alter_guardianprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgressReport',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه')], max_length=8)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('strengths', models.TextField(blank=True, default='')),
                ('improvements', models.TextField(blank=True, default='')),
                ('homework', models.TextField(blank=True, default='')),
                ('next_steps', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال\u200cشده')], default='draft', max_length=8)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_progress_reports', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_reports', to='education.courseoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_reports', to='persons.person')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['student', 'status', '-sent_at'], name='edu_progress_student_idx'), models.Index(fields=['author', 'offering', 'student'], name='edu_progress_author_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='edu_progress_date_range'), models.CheckConstraint(condition=models.Q(models.Q(('read_at__isnull', True), ('sent_at__isnull', True), ('status', 'draft')), models.Q(('sent_at__isnull', False), ('status', 'sent')), _connector='OR'), name='edu_progress_publication_state')],
            },
        ),
    ]
