# Generated by Django 5.1.15 on 2026-09-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playhouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='playhouseinvoice',
            new_name='playhouse_i_is_paid_93e244_idx',
            old_name='ph_inv_ispay_created_idx',
        ),
        migrations.RenameIndex(
            model_name='playhousesession',
            new_name='playhouse_s_session_44007c_idx',
            old_name='ph_sess_date_status_idx',
        ),
        migrations.AlterField(
            model_name='playhouseinvoiceseq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
