# Generated by Django 5.1.15 on 2026-09-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playhouse', '0004_config_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playhouseconfig',
            name='is_open_now',
            field=models.BooleanField(default=True, help_text='اگر خاموش باشد، ثبت ورود جدید مسدود می\u200cشود'),
        ),
    ]
